<a href="https://colab.research.google.com/github/manmeet3/Medical-SSL-SimCLRv2/blob/main/tf_data_test_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow.compat.v1 as tf
tf.enable_eager_execution()
import tensorflow_hub as hub
import tensorflow_datasets as tfds

In [2]:
batch_size = 64
dataset_name = 'tf_flowers'


In [3]:
tfds_dataset, tfds_info = tfds.load(
    dataset_name, split='train', with_info=True)
num_images = tfds_info.splits['train'].num_examples
num_classes = tfds_info.features['label'].num_classes

local data directory. If you'd instead prefer to read directly from our public
GCS bucket (recommended if you're running on GCP), you can instead pass
`try_gcs=True` to `tfds.load` or set `data_dir=gs://tfds-data/datasets`.





Dataset tf_flowers downloaded and prepared to /root/tensorflow_datasets/tf_flowers/3.0.1. Subsequent calls will reuse this data.


In [26]:
x = tfds_dataset

In [27]:
#x = tf.data.make_one_shot_iterator(x).get_next()

In [28]:
x
# this is what i want. Just need to figure out how to print tensors
# Tf needs to be initialized and have an active sesssion to print tensors. 
# -- https://towardsdatascience.com/getting-started-with-tensorflow-in-google-colaboratory-9a97458e1014

<PrefetchDataset shapes: {image: (None, None, 3), label: ()}, types: {image: tf.uint8, label: tf.int64}>

In [31]:
dir(x)

['_GeneratorState',
 '__abstractmethods__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_add_variable_with_custom_getter',
 '_apply_options',
 '_as_serialized_graph',
 '_buffer_size',
 '_checkpoint_dependencies',
 '_consumers',
 '_deferred_dependencies',
 '_flat_shapes',
 '_flat_structure',
 '_flat_types',
 '_functions',
 '_gather_saveables_for_checkpoint',
 '_graph',
 '_graph_attr',
 '_handle_deferred_dependencies',
 '_has_captured_ref',
 '_input_dataset',
 '_inputs',
 '_list_extra_dependencies_for_serializat

In [32]:
y=x.unbatch()

ValueError: ignored

In [7]:
import sys

In [8]:
indices = [0, 1, 2]
depth = 3

In [9]:
one_hot=tf.one_hot(indices,depth)

In [10]:
tf.keras.backend.print_tensor(one_hot)

 [[1 0 0]
 [0 1 0]
 [0 0 1]]


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [11]:
one_hot.get_shape()

TensorShape([3, 3])